package com.zhihaoliang.basicframe.mode.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DAO_INFO".
 */
@Entity
public class DaoInfo {

    @Id
    private Long id;
    /**
     * 手机账号
     */
    private String phone;
    private String password;
    private String empCode;
    private String orgCode;
    private String orgName;
    private String empName;
    private String encryptKey;
    private Integer deviceId;
    private Boolean isSavePassword;

    @Generated
    public DaoInfo() {
    }

    public DaoInfo(Long id) {
        this.id = id;
    }

    @Generated
    public DaoInfo(Long id, String phone, String password, String empCode, String orgCode, String orgName, String empName, String encryptKey, Integer deviceId, Boolean isSavePassword) {
        this.id = id;
        this.phone = phone;
        this.password = password;
        this.empCode = empCode;
        this.orgCode = orgCode;
        this.orgName = orgName;
        this.empName = empName;
        this.encryptKey = encryptKey;
        this.deviceId = deviceId;
        this.isSavePassword = isSavePassword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmpCode() {
        return empCode;
    }

    public void setEmpCode(String empCode) {
        this.empCode = empCode;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getEmpName() {
        return empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getEncryptKey() {
        return encryptKey;
    }

    public void setEncryptKey(String encryptKey) {
        this.encryptKey = encryptKey;
    }

    public Integer getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    public Boolean getIsSavePassword() {
        return isSavePassword;
    }

    public void setIsSavePassword(Boolean isSavePassword) {
        this.isSavePassword = isSavePassword;
    }

}
