package com.zhihaoliang.basicframe.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhihaoliang.basicframe.mode.database.DaoInfo;

import com.zhihaoliang.basicframe.dao.DaoInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoInfoDaoConfig;

    private final DaoInfoDao daoInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoInfoDaoConfig = daoConfigMap.get(DaoInfoDao.class).clone();
        daoInfoDaoConfig.initIdentityScope(type);

        daoInfoDao = new DaoInfoDao(daoInfoDaoConfig, this);

        registerDao(DaoInfo.class, daoInfoDao);
    }
    
    public void clear() {
        daoInfoDaoConfig.clearIdentityScope();
    }

    public DaoInfoDao getDaoInfoDao() {
        return daoInfoDao;
    }

}
